### ISSUE TITLE
Unable to run 1st example notebook

### ISSUE THREAD

**Issue by gstamatakis** [databloom-ai/BDE#1]
Greetings,

I'm having trouble running the first notebook under the examples directory.

I simply cloned the repository and run the following 2 commands to launch the Jupyter server via docker.

```bash
docker build -t blossom .
docker run -p 8888:8888 -v ${HOME}/.ivy2:/home/jovyan/.ivy2 blossom
```

Docker version: 20.10.14, build a224086

Was able to reproduce the error on Ubuntu 20.04, Windows 11 and WSL2.

**Error**
```
---------------------------------------------------------------------------
java.lang.RuntimeException: Exception occurred while running cell magic 'loadFromPOM': java.io.FileNotFoundException: /home/jovyan/.ivy2/cache/resolved-ijava.notebook-cell-1.xml (No such file or directory)
	at io.github.spencerpark.ijava.runtime.Magics.cellMagic(Magics.java:35)
	at .(#12:1)
```

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/13163237/166109842-b253fc4a-ec10-4058-8d32-047b6da10ace.png">

**Comment by berttty** [comment]
Hi @gstamatakis I was looking the error and I figure out that  the permission of the folder `${HOME}/.ivy2` are restricted just to write by the owner.

I suggest to run with 

```
docker run -p 8888:8888 -v $(pwd)/.ivy2:/home/jovyan/.ivy2 blossom
```

If you don't want to change the permission of the folder. 

Let us know if that solve the issue

**Comment by gstamatakis** [comment]
Thanks for the quick response, 
I'm afraid that didn't solve it either and I just ended up not mounting any volume at all (just skipped the -v command completely). I can report that the first example notebook is working as intended with that change. 
Feel free to close this issue as a workaround has been found, at least for me.

**Comment by berttty** [comment]
So nice that works for you too 😄, If you need something else let us know 👍
